package com.neoruaa.xhsdn

import com.neoruaa.xhsdn.data.settings.DownloadJson
import com.neoruaa.xhsdn.data.settings.DownloadOptions
import com.neoruaa.xhsdn.data.settings.LivePhotoFormat
import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import javax.xml.parsers.DocumentBuilderFactory
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

class MotionPhotoContainerTest {
    @get:Rule val temp = TemporaryFolder()
    private val jpeg = byteArrayOf(0xff.toByte(), 0xd8.toByte(), 0xff.toByte(), 0xd9.toByte())
    private val video = box("ftyp", "isom0000".toByteArray()) + box("moov", byteArrayOf(1)) + box("mdat", ByteArray(128) { it.toByte() })

    private fun reference(name: String) = javaClass.getResourceAsStream("/livephoto/$name")!!.use { it.readBytes() }

    @Test fun binaryEnvelopesMatchPinnedOpenSourceReferences() {
        val (samsung, samsungLayout) = write(LivePhotoFormat.SAMSUNG)
        assertArrayEquals(reference("samsung-jpeg-trailer.bin"), samsung.readBytes().copyOfRange((samsungLayout.videoOffset - 24).toInt(), samsung.length().toInt()))
        val (oplus, oplusLayout) = write(LivePhotoFormat.OPLUS)
        val oplusBytes = oplus.readBytes()
        val segmentStart = String(oplusBytes, Charsets.ISO_8859_1).indexOf("MPF\u0000") - 4
        val mpf = reference("oplus-mpf-4096.bin")
        ByteBuffer.wrap(mpf).putInt(62, oplusLayout.videoOffset.toInt())
        assertArrayEquals(mpf, oplusBytes.copyOfRange(segmentStart, segmentStart + mpf.size))
        val id = "0123456789abcdef0123456789ab"
        assertArrayEquals(reference("vivo-image-tail.bin"), MotionPhotoContainer.vivoImageTail(id))
        assertArrayEquals(reference("vivo-video-uuid.bin"), MotionPhotoContainer.vivoVideoBox(id))
        val (huawei, _) = write(LivePhotoFormat.HUAWEI)
        assertArrayEquals(reference("huawei-tail.bin"), huawei.readBytes().takeLast(60).toByteArray())
    }

    @Test fun vivoSdrMetadataMatchesUpstreamIncludingCompleteUserComment() {
        fun fields(xml: ByteArray): List<Map<String, String>> {
            val document = DocumentBuilderFactory.newInstance().apply { isNamespaceAware = true }
                .newDocumentBuilder().parse(xml.inputStream())
            val nodes = document.getElementsByTagName("*")
            return (0 until nodes.length).map { nodes.item(it) }.filter { it.localName in setOf("Description", "Item") }.map { node ->
                (0 until node.attributes.length).map { node.attributes.item(it) }
                    .filter { it.namespaceURI != "http://www.w3.org/2000/xmlns/" }
                    .associate { "${it.namespaceURI}:${it.localName}" to it.nodeValue }
            }
        }
        assertEquals(fields(reference("vivo-sdr-reference.xmp")), fields(MotionPhotoContainer.xmp(LivePhotoFormat.VIVO, video.size.toLong(), 0, "video/mp4").toByteArray()))
        assertEquals(String(reference("vivo-user-comment.txt")), LivePhotoCreator.vivoUserComment("2000:01:01 00:00:00"))
    }

    @Test fun oplusUsesReferenceCoverTimestampAndDirectoryPadding() {
        val xml = MotionPhotoContainer.xmp(LivePhotoFormat.OPLUS, video.size.toLong(), 0, "video/mp4")
        assertTrue(xml.contains("GCamera:MotionPhotoPresentationTimestampUs=\"0\""))
        assertTrue(xml.contains("OpCamera:MotionPhotoPrimaryPresentationTimestampUs=\"0\""))
        assertTrue(xml.contains("OpCamera:MotionPhotoOwner=\"oplus\""))
        assertTrue(xml.contains("Item:Length=\"${video.size}\" Item:Padding=\"0\""))
    }

    @Test fun xiaomiOutputMatchesThePreviouslyWorkingWriterByteForByte() {
        // Frozen from the pre-multiformat implementation, not generated by the current writer.
        val baseline = javaClass.getResourceAsStream("/livephoto/xiaomi-before-multiformat.xmp")!!
            .bufferedReader().use { it.readText() }.replace("@VIDEO_LENGTH@", video.size.toString())
        val payload = "http://ns.adobe.com/xap/1.0/\u0000".toByteArray() + baseline.toByteArray()
        val app1 = ByteArrayOutputStream().also { bytes -> DataOutputStream(bytes).use {
            it.writeShort(0xffe1); it.writeShort(payload.size + 2); it.write(payload)
        } }.toByteArray()
        val app0 = byteArrayOf(0xff.toByte(), 0xe0.toByte(), 0, 7) + "JFIF\u0000".toByteArray()
        val cover = jpeg.copyOfRange(0, 2) + app0 + jpeg.copyOfRange(2, jpeg.size)
        val image = temp.newFile().apply { writeBytes(cover) }
        val clip = temp.newFile().apply { writeBytes(video) }
        val expected = cover.copyOfRange(0, 2) + app1 + cover.copyOfRange(2, cover.size) + video
        for (format in listOf(LivePhotoFormat.XIAOMI, LivePhotoFormat.AUTO.resolve("Xiaomi", "Redmi"))) {
            val output = temp.newFile()
            MotionPhotoContainer.write(image, clip, output, format, "video/mp4", 18)
            assertArrayEquals(expected, output.readBytes())
        }
    }

    @Test fun allSingleFileFormatsPreserveVideoAndDeclareItsActualOffset() {
        for (format in LivePhotoFormat.entries.filter { it !in listOf(LivePhotoFormat.AUTO, LivePhotoFormat.VIVO_LEGACY) }) {
            val (output, layout) = write(format)
            val data = output.readBytes()
            assertArrayEquals(format.name, video, data.copyOfRange(layout.videoOffset.toInt(), (layout.videoOffset + layout.videoLength).toInt()))
            assertEquals(data.size.toLong(), layout.totalLength)
            if (format == LivePhotoFormat.HUAWEI) {
                assertEquals("LIVE_${video.size + 20}", String(data.copyOfRange(data.size - 20, data.size)).trim())
                assertEquals("0:18", String(data.copyOfRange(data.size - 40, data.size - 20)).trim())
            } else {
                val text = String(data, Charsets.ISO_8859_1)
                val xml = text.substring(text.indexOf("<x:xmpmeta"), text.indexOf("</x:xmpmeta>") + 12)
                val factory = DocumentBuilderFactory.newInstance().apply { isNamespaceAware = true }
                val document = factory.newDocumentBuilder().parse(xml.byteInputStream())
                val itemNs = "http://ns.google.com/photos/1.0/container/item/"
                val items = document.getElementsByTagNameNS("http://ns.google.com/photos/1.0/container/", "Item")
                val motion = items.item(1) as org.w3c.dom.Element
                val length = motion.getAttributeNS(itemNs, "Length").toLong()
                assertEquals(layout.videoOffset, data.size - length)
                val primary = items.item(0) as org.w3c.dom.Element
                assertEquals(when (format) { LivePhotoFormat.SAMSUNG -> "24"; LivePhotoFormat.VIVO -> ""; else -> "0" }, primary.getAttributeNS(itemNs, "Padding"))
                assertEquals("video/mp4", motion.getAttributeNS(itemNs, "Mime"))
            }
        }
    }

    @Test fun samsungIndexLocatesBothFieldsIndependentlyOfXmp() {
        val (output, layout) = write(LivePhotoFormat.SAMSUNG)
        val bytes = output.readBytes()
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        val indexLength = buffer.getInt(bytes.size - 8)
        val index = bytes.size - 8 - indexLength
        assertEquals("SEFH", String(bytes, index, 4))
        assertEquals(107, buffer.getInt(index + 4))
        assertEquals(2, buffer.getInt(index + 8))
        val dataStart = index - buffer.getInt(index + 16)
        assertEquals(layout.videoOffset - 24, dataStart.toLong())
        assertEquals(video.size + 24, buffer.getInt(index + 20))
        assertEquals("MotionPhoto_Data", String(bytes, dataStart + 8, 16))
        val versionStart = index - buffer.getInt(index + 28)
        assertEquals("MotionPhoto_Versionmpv3", String(bytes, versionStart + 8, 23))
        assertEquals("SEFT", String(bytes, bytes.size - 4, 4))
    }

    @Test fun oplusMpfReferencesFinalJpegSize() {
        val (output, layout) = write(LivePhotoFormat.OPLUS)
        val data = output.readBytes()
        val mpf = String(data, Charsets.ISO_8859_1).indexOf("MPF\u0000")
        val tiff = mpf + 4
        val buffer = ByteBuffer.wrap(data).order(ByteOrder.BIG_ENDIAN)
        assertEquals(1, buffer.getInt(tiff + 30))
        assertEquals(0x00030000, buffer.getInt(tiff + 50))
        assertEquals(layout.videoOffset.toInt(), buffer.getInt(tiff + 54))
        assertTrue(String(data).contains("OpCamera:MotionPhotoFeatureFlag=\"1\""))
        assertFalse(String(data).contains("MicroVideoOffset"))
    }

    @Test fun pairedVivoUsesSameIdAndValidUuidSize() {
        val id = "0123456789abcdef0123456789ab"
        val image = MotionPhotoContainer.vivoImageTail(id)
        val video = MotionPhotoContainer.vivoVideoBox(id)
        assertEquals(video.size, ByteBuffer.wrap(video).int)
        assertEquals("uuid", String(video, 4, 4))
        assertArrayEquals("vivoMediaExtInfo".toByteArray(), video.copyOfRange(8, 24))
        for (data in listOf(image, video)) {
            val album = String(data, Charsets.ISO_8859_1).indexOf("cameralbum!")
            assertEquals(47, ByteBuffer.wrap(data).getInt(album + 11))
            assertEquals(id, String(data, album + 15, 28))
            assertTrue(String(data).contains("\"com.android.camera.livephoto\":\"$id\""))
        }
    }

    @Test fun rejectsTruncatedAndNonVideoInput() {
        val file = temp.newFile()
        for (invalid in listOf(byteArrayOf(), "<html>error</html>".toByteArray(), video.copyOf(video.size - 1), box("ftyp", "isom0000".toByteArray()))) {
            file.writeBytes(invalid)
            assertThrows(java.io.IOException::class.java) { MotionPhotoContainer.videoMime(file) }
        }
        file.writeBytes(video)
        assertEquals("video/mp4", MotionPhotoContainer.videoMime(file))
    }

    @Test fun cancellationEscapesWriterAndLargeOffsetsDoNotOverflow() {
        val image = temp.newFile().apply { writeBytes(jpeg) }
        val clip = temp.newFile().apply { writeBytes(video) }
        assertThrows(java.util.concurrent.CancellationException::class.java) {
            MotionPhotoContainer.write(image, clip, temp.newFile(), LivePhotoFormat.STANDARD, "video/mp4", 0) {
                throw java.util.concurrent.CancellationException()
            }
        }
        val length = Int.MAX_VALUE.toLong() + 123
        val xmp = MotionPhotoContainer.xmp(LivePhotoFormat.XIAOMI, length, 0, "video/mp4")
        assertTrue(xmp.contains("MicroVideoOffset=\"$length\""))
        assertTrue(xmp.contains("Item:Length=\"$length\""))
    }

    @Test fun oldSettingsDefaultToAutomaticAndManualSelectionWins() {
        assertEquals(LivePhotoFormat.AUTO, DownloadJson.decodeFromString<DownloadOptions>("{}").livePhotoFormat)
        assertEquals(LivePhotoFormat.OPLUS, LivePhotoFormat.AUTO.resolve("OnePlus", "oneplus"))
        assertEquals(LivePhotoFormat.XIAOMI, LivePhotoFormat.AUTO.resolve("unknown", "POCO"))
        assertEquals(LivePhotoFormat.VIVO, LivePhotoFormat.AUTO.resolve("vivo", "iQOO"))
        assertEquals(LivePhotoFormat.STANDARD, LivePhotoFormat.AUTO.resolve("unknown", "unknown"))
        assertEquals(LivePhotoFormat.SAMSUNG, LivePhotoFormat.SAMSUNG.resolve("Xiaomi", "redmi"))
    }

    private fun write(format: LivePhotoFormat): Pair<File, MotionPhotoContainer.Layout> {
        val image = temp.newFile().apply { writeBytes(jpeg) }
        val clip = temp.newFile().apply { writeBytes(video) }
        val output = temp.newFile()
        return output to MotionPhotoContainer.write(image, clip, output, format, "video/mp4", 18)
    }

    private fun box(type: String, data: ByteArray): ByteArray = ByteArrayOutputStream().also { output ->
        DataOutputStream(output).use { it.writeInt(8 + data.size); it.writeBytes(type); it.write(data) }
    }.toByteArray()
}
